export type Project = {
  slug: string;
  title: string;
  location: string;
  category: string;
  /** Omitted where the studio hasn't confirmed a completion year. */
  year?: string;
  /** Poster still, generated by scripts/build-media.mjs. */
  image: string;
  description: string;
  highlights: string[];
  /**
   * Folder under /public/media holding the scroll-scrub frame sequence.
   * `startFrame` skips a leading title card where the film opens on one.
   * `scrollLength` overrides the default 3.5 viewports of scrub, which is
   * tuned for the ~120-frame sets — a longer sequence needs proportionally
   * more scroll or it races past.
   */
  media?: {
    slug: string;
    frameCount: number;
    startFrame?: number;
    scrollLength?: number;
  };
  /** Equirectangular 360° image (2:1), self-hosted under /public/panoramas. */
  panorama?: string;
};

/** Plate aspect for the phone builds. Mirrors MOBILE_ASPECT in the manifest. */
const MOBILE_ASPECT = 0.8;

/**
 * The phone build of a film, which every set in the manifest now has: same
 * cut, cropped to a portrait plate, at half the frames.
 *
 * Derived rather than listed per project so there is one place the two builds
 * can disagree instead of six. It has to match `mobileOf` in
 * scripts/media-manifest.mjs — if that ever stops being "half the desktop
 * count", check public/media/<slug>-mobile/meta.json and change both.
 *
 * scrollLength is a flat 3 rather than the desktop value: the phone sets are
 * half the length, so reusing the desktop scroll would halve the apparent
 * camera speed and leave the visitor scrolling twice as far for it.
 */
export function mobileMediaFor(media: NonNullable<Project["media"]>) {
  return {
    slug: `${media.slug}-mobile`,
    frameCount: Math.round(media.frameCount / 2),
    scrollLength: 3,
    aspect: MOBILE_ASPECT,
  };
}

// Descriptions are written from the studio's own presentation films — every
// feature named below is visible in the renders. Years, areas and client
// attributions are deliberately left out where the studio hasn't confirmed
// them rather than guessed at.
export const PROJECTS: Project[] = [
  {
    slug: "shiv-shrushti-baramati",
    title: "Shiv Shrushti",
    location: "Baramati, Maharashtra",
    category: "Cultural Landmark",
    image: "/media/shiv-shrushti/poster.webp",
    description:
      "A monumental heritage precinct conceived as the landmark arrival point for Baramati. Fort-inspired stone ramparts step along the approach road and rise into a carved timber-galleried gateway, while bronze equestrian sculptures, period cannons and torch-lit niches turn the forecourt into a ceremonial civic space rather than a simple entrance.",
    highlights: [
      "Fort-scale rampart walls with sculpted warrior niches",
      "Ceremonial forecourt with fountain court and processional steps",
      "Illuminated stonework designed to read by day and by firelight",
    ],
    // 180 frames, up from 120: the cut now carries a second window in which
    // the gateway's timber doors swing open and the camera passes through to
    // the memorial avenue — the film's ending. See media-manifest.mjs.
    //
    // scrollLength rises with the count. Left at the 3.5 default these 180
    // frames would run at 51 per viewport against the 34 this film has
    // always scrubbed at, and the whole thing would race past in the same
    // scroll distance as before.
    media: { slug: "shiv-shrushti", frameCount: 180, scrollLength: 5.5 },
  },
  {
    slug: "yamai-devi-lake",
    title: "Yamai Devi Lake Development",
    location: "Aundh, Satara",
    category: "Landscape & Public Realm",
    image: "/media/yamai-lake/poster.webp",
    description:
      "A lake and gram-park redevelopment that returns the water's edge to the town. The scheme threads a continuous promenade around the lake, anchoring it with a ritual ghat, a sculpted heritage wall, a fountain plaza and shaded pergola courts, then layers in swings, play areas and timber bridges so the whole family finds a reason to stay.",
    highlights: [
      "Continuous lakeside promenade with ghat and ritual space",
      "Sculpture wall, fountain plaza and shaded pergola courts",
      "Play areas, large swings and timber bridge crossings",
    ],
    // startFrame 11 clears the title burnt into the opening seconds
    // ("DEVELOPMENT OF YAMI AND GRAM LAKE" over the lake render), which
    // frame 12 is the first to be free of. It has always been there; the
    // portrait crop is what made it unmissable, since the centre cut lands
    // mid-word. The studio's watermark and shot captions are burnt in
    // throughout the film and cannot be skipped this way — though the crop
    // does put the top-right mark outside the frame.
    media: { slug: "yamai-lake", frameCount: 120, startFrame: 11 },
  },
  {
    slug: "ss-villa-lucknow",
    title: "SS Villa",
    location: "Lucknow, Uttar Pradesh",
    category: "Residential",
    image: "/media/ss-villa-lucknow/poster.webp",
    description:
      "A contemporary villa that answers a hot climate with a screen. Perforated jali panels wrap the white massing to filter light and hold privacy at the street, while the plan opens inward and upward — a sheltered arrival court, a double-height lounge, and a pool terrace on the upper floor that borrows the skyline as its view.",
    highlights: [
      "Perforated jali façade for shading and privacy",
      "Sheltered arrival court with covered drop-off",
      "First-floor lounge opening onto a pool terrace",
    ],
    media: { slug: "ss-villa-lucknow", frameCount: 120 },
  },
  {
    slug: "nashik-hillside-villa",
    title: "Hillside Villa, Nashik",
    location: "Nashik, Maharashtra",
    category: "Residential",
    image: "/media/nashik-villa/poster.webp",
    description:
      "A modern family residence set against the Nashik hills, planned so that the valley is present in every principal room. Deep horizontal eaves and full-height glazing frame the landscape, while the outdoor rooms do the entertaining — a sunken bonfire sit-out, a water-edge deck with barbeque gazebo, and a pool terrace that runs the length of the house.",
    highlights: [
      "Valley-facing living spaces behind full-height glazing",
      "Sunken bonfire sit-out and water-edge barbeque deck",
      "Six bedrooms across ground and first floors",
    ],
    // Same media folder as the homepage hero: the studio's own six-shot
    // cover sequence, built from their per-shot 4K masters. frameCount must
    // match public/media/nashik-villa/meta.json. scrollLength is raised from
    // the 3.5 the ~120-frame sets use because this one is half as long
    // again — at 5 it scrubs at the same speed they do.
    media: { slug: "nashik-villa", frameCount: 180, scrollLength: 5 },
  },
  {
    slug: "apti-hillside-estate",
    title: "Apti Hillside Estate",
    location: "Apti, Maharashtra",
    category: "Residential",
    image: "/media/apti-villa/poster.webp",
    description:
      "A Mediterranean-inspired estate built into a steep, wooded slope. Arched colonnades and terracotta roofs step down the hillside so no level blocks another, and the landscape does the rest — an infinity pool reading straight into the valley, a rock-and-waterfall garden, bonfire terrace, and a gazebo reached by a bridge over the stream.",
    highlights: [
      "Arched colonnades and terracotta roofs terraced into the slope",
      "Infinity-edge pool overlooking the valley",
      "Rock waterfall garden with bridge and gazebo seating",
    ],
    media: { slug: "apti-villa", frameCount: 120 },
  },
  {
    slug: "ulwe-penthouse",
    title: "Ulwe Penthouse",
    location: "Ulwe, Navi Mumbai",
    category: "Interior Design",
    image: "/media/ulwe-penthouse/poster.webp",
    description:
      "A four-bedroom penthouse interior on the twelfth floor, resolved as one continuous material idea. Warm travertine, fluted timber and brushed brass carry through every room; layered cove and track lighting lets the same spaces read bright by day and intimate at night, from the open living and dining volume to a dedicated namaz room.",
    highlights: [
      "Open-plan living and dining with sculpted ceiling coves",
      "Modular kitchen with full-height storage wall",
      "Three bedrooms plus a dedicated namaz room",
    ],
    // startFrame 5 skips the film's title card — four black frames carrying
    // the client's name and address, which is neither the studio's work nor
    // something to publish. Frame 6 is the first clean render. The manifest's
    // `start: 4` was meant to trim this and lands a beat short.
    media: { slug: "ulwe-penthouse", frameCount: 150, startFrame: 5 },
  },
];

export function getProjectBySlug(slug: string) {
  return PROJECTS.find((project) => project.slug === slug);
}
