/**
 * Bakes real world coastlines into a static path file.
 *
 * Source is Natural Earth's `land` object via world-atlas — landmass only,
 * with no country borders in the data at all. That is deliberate: the launch
 * page shows a gold world silhouette, and drawing national boundaries would
 * mean taking a position on every disputed border on the map.
 *
 * Run with: node scripts/build-world.mjs
 * Output:   lib/world-land.generated.ts  (committed; no runtime dependency)
 */

import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = require("world-atlas/land-110m.json");

// Must match MAP_BOUNDS / UNITS_PER_DEG in lib/india-map.ts
const MIN_LON = -180;
const MAX_LON = 180;
const MIN_LAT = -58;
const MAX_LAT = 84;
const UNITS_PER_DEG = 10;

function project([lon, lat]) {
  const x = (lon - MIN_LON) * UNITS_PER_DEG;
  const y = (MAX_LAT - lat) * UNITS_PER_DEG;
  return [x, y];
}

/** Drop rings smaller than this many degrees across — specks add weight only. */
const MIN_SPAN_DEG = 1.1;

/**
 * Splits a ring wherever it leaves the projection window or wraps across the
 * antimeridian. Clamping instead of splitting is what produced full-width
 * horizontal streaks: Antarctica pinned flat along the bottom edge, and
 * Chukotka jumping from +180 to -180 in a single segment.
 */
function splitRing(ring) {
  const runs = [];
  let current = [];
  let prevLon = null;

  for (const [lon, lat] of ring) {
    const outside = lat < MIN_LAT || lat > MAX_LAT;
    const wraps = prevLon !== null && Math.abs(lon - prevLon) > 180;

    if (outside || wraps) {
      if (current.length > 3) runs.push(current);
      current = [];
      prevLon = outside ? null : lon;
      if (outside) continue;
    }

    current.push([lon, lat]);
    prevLon = lon;
  }
  if (current.length > 3) runs.push(current);
  return runs;
}

function ringToPath(ring) {
  let minLon = Infinity;
  let maxLon = -Infinity;
  let minLat = Infinity;
  let maxLat = -Infinity;
  for (const [lon, lat] of ring) {
    minLon = Math.min(minLon, lon);
    maxLon = Math.max(maxLon, lon);
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
  }
  if (maxLon - minLon < MIN_SPAN_DEG && maxLat - minLat < MIN_SPAN_DEG) {
    return null;
  }

  // The world view is ~3600 units across rendered into ~1200px, so anything
  // finer than a unit or two is invisible. Thinning here is what keeps the
  // generated file small enough to ship.
  const MIN_SEG = 2.5;
  const parts = [];
  let prev = null;
  for (const point of ring) {
    const [x, y] = project(point);
    const rx = Math.round(x);
    const ry = Math.round(y);
    if (prev && Math.hypot(rx - prev[0], ry - prev[1]) < MIN_SEG) continue;
    parts.push(`${parts.length === 0 ? "M" : "L"}${rx} ${ry}`);
    prev = [rx, ry];
  }
  return parts.length > 3 ? `${parts.join(" ")} Z` : null;
}

const land = feature(topo, topo.objects.land);
const paths = [];

for (const geom of land.features) {
  const polys =
    geom.geometry.type === "Polygon"
      ? [geom.geometry.coordinates]
      : geom.geometry.coordinates;
  for (const poly of polys) {
    // Ring 0 is the outer boundary; the rest are holes (inland seas).
    for (const ring of poly) {
      for (const run of splitRing(ring)) {
        const d = ringToPath(run);
        if (d) paths.push(d);
      }
    }
  }
}

paths.sort((a, b) => b.length - a.length);

const out = `// GENERATED by scripts/build-world.mjs — do not edit by hand.
// Natural Earth land polygons (landmass only, no national borders),
// pre-projected to the equirectangular window in lib/india-map.ts.

export const WORLD_LAND: string[] = ${JSON.stringify(paths, null, 0).replace(
  /","/g,
  '",\n  "'
).replace(/^\[/, "[\n  ").replace(/\]$/, ",\n]")};
`;

writeFileSync(new URL("../lib/world-land.generated.ts", import.meta.url), out);
console.log(`wrote ${paths.length} rings, ${(out.length / 1024).toFixed(0)} KB`);
